# Generated by Django 2.2.6 on 2023-04-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('kayak_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('route_map', models.ImageField(upload_to='routes')),
            ],
        ),
        migrations.CreateModel(
            name='planned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajak.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('participants', models.IntegerField()),
                ('kayak_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('payment', models.BooleanField()),
                ('mail', models.EmailField(max_length=128)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajak.Route')),
            ],
        ),
    ]
