# Generated by Django 4.2 on 2023-05-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kajak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('participants', models.IntegerField()),
                ('phone_number', models.CharField(max_length=12)),
                ('payment', models.BooleanField()),
                ('mail', models.EmailField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='kayak',
            name='seats',
            field=models.IntegerField(choices=[(1, 'jednoosobowy'), (2, 'dwuosobowy'), (3, 'rodzinny')], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AddField(
            model_name='reservation',
            name='kayaks',
            field=models.ManyToManyField(to='kajak.kayak'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kajak.message'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajak.route'),
        ),
    ]
